# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import circle_ci_python_sdk
from circle_ci_python_sdk.paths.project_project_slug_pipeline import post
from circle_ci_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestProjectProjectSlugPipeline(ApiTestMixin, unittest.TestCase):
    """
    ProjectProjectSlugPipeline unit test stubs
        Trigger a new pipeline
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 201




if __name__ == '__main__':
    unittest.main()
