# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from circle_ci_python_sdk import schemas  # noqa: F401


class InsightsGetWorkflowSummaryMetricsResponse(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Workflow level aggregated metrics and trends response
    """


    class MetaOapg:
        required = {
            "workflow_names",
            "metrics",
            "trends",
        }
        
        class properties:
        
            @staticmethod
            def metrics() -> typing.Type['InsightsGetWorkflowSummaryMetricsResponseMetrics']:
                return InsightsGetWorkflowSummaryMetricsResponseMetrics
        
            @staticmethod
            def trends() -> typing.Type['InsightsGetWorkflowSummaryMetricsResponseTrends']:
                return InsightsGetWorkflowSummaryMetricsResponseTrends
        
            @staticmethod
            def workflow_names() -> typing.Type['InsightsGetWorkflowSummaryMetricsResponseWorkflowNames']:
                return InsightsGetWorkflowSummaryMetricsResponseWorkflowNames
            __annotations__ = {
                "metrics": metrics,
                "trends": trends,
                "workflow_names": workflow_names,
            }
    
    workflow_names: 'InsightsGetWorkflowSummaryMetricsResponseWorkflowNames'
    metrics: 'InsightsGetWorkflowSummaryMetricsResponseMetrics'
    trends: 'InsightsGetWorkflowSummaryMetricsResponseTrends'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metrics"]) -> 'InsightsGetWorkflowSummaryMetricsResponseMetrics': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["trends"]) -> 'InsightsGetWorkflowSummaryMetricsResponseTrends': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["workflow_names"]) -> 'InsightsGetWorkflowSummaryMetricsResponseWorkflowNames': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["metrics", "trends", "workflow_names", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metrics"]) -> 'InsightsGetWorkflowSummaryMetricsResponseMetrics': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["trends"]) -> 'InsightsGetWorkflowSummaryMetricsResponseTrends': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["workflow_names"]) -> 'InsightsGetWorkflowSummaryMetricsResponseWorkflowNames': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["metrics", "trends", "workflow_names", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        workflow_names: 'InsightsGetWorkflowSummaryMetricsResponseWorkflowNames',
        metrics: 'InsightsGetWorkflowSummaryMetricsResponseMetrics',
        trends: 'InsightsGetWorkflowSummaryMetricsResponseTrends',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'InsightsGetWorkflowSummaryMetricsResponse':
        return super().__new__(
            cls,
            *args,
            workflow_names=workflow_names,
            metrics=metrics,
            trends=trends,
            _configuration=_configuration,
            **kwargs,
        )

from circle_ci_python_sdk.model.insights_get_workflow_summary_metrics_response_metrics import InsightsGetWorkflowSummaryMetricsResponseMetrics
from circle_ci_python_sdk.model.insights_get_workflow_summary_metrics_response_trends import InsightsGetWorkflowSummaryMetricsResponseTrends
from circle_ci_python_sdk.model.insights_get_workflow_summary_metrics_response_workflow_names import InsightsGetWorkflowSummaryMetricsResponseWorkflowNames
