# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from circle_ci_python_sdk import schemas  # noqa: F401


class PipelineGetByNumberResponseErrors(
    schemas.ListSchema
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)

    A sequence of errors that have occurred within the pipeline.
    """


    class MetaOapg:
        
        @staticmethod
        def items() -> typing.Type['PipelineGetByNumberResponseErrorsItem']:
            return PipelineGetByNumberResponseErrorsItem

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple['PipelineGetByNumberResponseErrorsItem'], typing.List['PipelineGetByNumberResponseErrorsItem']],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'PipelineGetByNumberResponseErrors':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> 'PipelineGetByNumberResponseErrorsItem':
        return super().__getitem__(i)

from circle_ci_python_sdk.model.pipeline_get_by_number_response_errors_item import PipelineGetByNumberResponseErrorsItem
