# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from circle_ci_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from circle_ci_python_sdk.api_response import AsyncGeneratorResponse
from circle_ci_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from circle_ci_python_sdk import schemas  # noqa: F401

from circle_ci_python_sdk.model.workflow_approve_job_response import WorkflowApproveJobResponse as WorkflowApproveJobResponseSchema
from circle_ci_python_sdk.model.workflow_approve_jobdefault_response import WorkflowApproveJobdefaultResponse as WorkflowApproveJobdefaultResponseSchema

from circle_ci_python_sdk.type.workflow_approve_jobdefault_response import WorkflowApproveJobdefaultResponse
from circle_ci_python_sdk.type.workflow_approve_job_response import WorkflowApproveJobResponse

from ...api_client import Dictionary
from circle_ci_python_sdk.pydantic.workflow_approve_jobdefault_response import WorkflowApproveJobdefaultResponse as WorkflowApproveJobdefaultResponsePydantic
from circle_ci_python_sdk.pydantic.workflow_approve_job_response import WorkflowApproveJobResponse as WorkflowApproveJobResponsePydantic

from . import path

# Path params
ApprovalRequestIdSchema = schemas.UUIDSchema
IdSchema = schemas.UUIDSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'approval_request_id': typing.Union[ApprovalRequestIdSchema, str, uuid.UUID, ],
        'id': typing.Union[IdSchema, str, uuid.UUID, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_approval_request_id = api_client.PathParameter(
    name="approval_request_id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=ApprovalRequestIdSchema,
    required=True,
)
request_path_id = api_client.PathParameter(
    name="id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=IdSchema,
    required=True,
)
_auth = [
    'api_key_header',
    'api_key_query',
    'basic_auth',
]
SchemaFor202ResponseBodyApplicationJson = WorkflowApproveJobResponseSchema


@dataclass
class ApiResponseFor202(api_client.ApiResponse):
    body: WorkflowApproveJobResponse


@dataclass
class ApiResponseFor202Async(api_client.AsyncApiResponse):
    body: WorkflowApproveJobResponse


_response_for_202 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor202,
    response_cls_async=ApiResponseFor202Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor202ResponseBodyApplicationJson),
    },
)
SchemaFor0ResponseBodyApplicationJson = WorkflowApproveJobdefaultResponseSchema


@dataclass
class ApiResponseForDefault(api_client.ApiResponse):
    body: WorkflowApproveJobdefaultResponse


@dataclass
class ApiResponseForDefaultAsync(api_client.AsyncApiResponse):
    body: WorkflowApproveJobdefaultResponse


_response_for_default = api_client.OpenApiResponse(
    response_cls=ApiResponseForDefault,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor0ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '202': _response_for_202,
    'default': _response_for_default,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _approve_job_mapped_args(
        self,
        approval_request_id: str,
        id: str,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        if approval_request_id is not None:
            _path_params["approval_request_id"] = approval_request_id
        if id is not None:
            _path_params["id"] = id
        args.path = _path_params
        return args

    async def _aapprove_job_oapg(
        self,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor202Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Approve a job
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_approval_request_id,
            request_path_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/workflow/{id}/approve/{approval_request_id}',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserializationAsync(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _approve_job_oapg(
        self,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor202,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Approve a job
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_approval_request_id,
            request_path_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/workflow/{id}/approve/{approval_request_id}',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class ApproveJobRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aapprove_job(
        self,
        approval_request_id: str,
        id: str,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor202Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._approve_job_mapped_args(
            approval_request_id=approval_request_id,
            id=id,
        )
        return await self._aapprove_job_oapg(
            path_params=args.path,
            **kwargs,
        )
    
    def approve_job(
        self,
        approval_request_id: str,
        id: str,
    ) -> typing.Union[
        ApiResponseFor202,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._approve_job_mapped_args(
            approval_request_id=approval_request_id,
            id=id,
        )
        return self._approve_job_oapg(
            path_params=args.path,
        )

class ApproveJob(BaseApi):

    async def aapprove_job(
        self,
        approval_request_id: str,
        id: str,
        validate: bool = False,
        **kwargs,
    ) -> WorkflowApproveJobResponsePydantic:
        raw_response = await self.raw.aapprove_job(
            approval_request_id=approval_request_id,
            id=id,
            **kwargs,
        )
        if validate:
            return WorkflowApproveJobResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(WorkflowApproveJobResponsePydantic, raw_response.body)
    
    
    def approve_job(
        self,
        approval_request_id: str,
        id: str,
        validate: bool = False,
    ) -> WorkflowApproveJobResponsePydantic:
        raw_response = self.raw.approve_job(
            approval_request_id=approval_request_id,
            id=id,
        )
        if validate:
            return WorkflowApproveJobResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(WorkflowApproveJobResponsePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        approval_request_id: str,
        id: str,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor202Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._approve_job_mapped_args(
            approval_request_id=approval_request_id,
            id=id,
        )
        return await self._aapprove_job_oapg(
            path_params=args.path,
            **kwargs,
        )
    
    def post(
        self,
        approval_request_id: str,
        id: str,
    ) -> typing.Union[
        ApiResponseFor202,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._approve_job_mapped_args(
            approval_request_id=approval_request_id,
            id=id,
        )
        return self._approve_job_oapg(
            path_params=args.path,
        )

