# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

import unittest

import circle_ci_python_sdk
from circle_ci_python_sdk.model.policy_management_evaluate_input_data401_response import PolicyManagementEvaluateInputData401Response
from circle_ci_python_sdk import configuration


class TestPolicyManagementEvaluateInputData401Response(unittest.TestCase):
    """PolicyManagementEvaluateInputData401Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
