# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

import unittest

import circle_ci_python_sdk
from circle_ci_python_sdk.model.insights_get_summary_metrics_with_trends_response_org_data_trends import InsightsGetSummaryMetricsWithTrendsResponseOrgDataTrends
from circle_ci_python_sdk import configuration


class TestInsightsGetSummaryMetricsWithTrendsResponseOrgDataTrends(unittest.TestCase):
    """InsightsGetSummaryMetricsWithTrendsResponseOrgDataTrends unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
