# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

import unittest

import circle_ci_python_sdk
from circle_ci_python_sdk.model.project_get_by_slug_response import ProjectGetBySlugResponse
from circle_ci_python_sdk import configuration


class TestProjectGetBySlugResponse(unittest.TestCase):
    """ProjectGetBySlugResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
