# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

import unittest

import circle_ci_python_sdk
from circle_ci_python_sdk.model.context_get_restrictions401_response import ContextGetRestrictions401Response
from circle_ci_python_sdk import configuration


class TestContextGetRestrictions401Response(unittest.TestCase):
    """ContextGetRestrictions401Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
