# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

import unittest

import circle_ci_python_sdk
from circle_ci_python_sdk.model.job_get_test_metadatadefault_response import JobGetTestMetadatadefaultResponse
from circle_ci_python_sdk import configuration


class TestJobGetTestMetadatadefaultResponse(unittest.TestCase):
    """JobGetTestMetadatadefaultResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
