# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

import unittest

import circle_ci_python_sdk
from circle_ci_python_sdk.model.workflow_get_by_iddefault_response import WorkflowGetByIddefaultResponse
from circle_ci_python_sdk import configuration


class TestWorkflowGetByIddefaultResponse(unittest.TestCase):
    """WorkflowGetByIddefaultResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
