# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

import unittest

import circle_ci_python_sdk
from circle_ci_python_sdk.model.context_list_environment_variables_response_items_item import ContextListEnvironmentVariablesResponseItemsItem
from circle_ci_python_sdk import configuration


class TestContextListEnvironmentVariablesResponseItemsItem(unittest.TestCase):
    """ContextListEnvironmentVariablesResponseItemsItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
