# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from circle_ci_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from circle_ci_python_sdk.api_response import AsyncGeneratorResponse
from circle_ci_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from circle_ci_python_sdk import schemas  # noqa: F401

from circle_ci_python_sdk.model.insights_get_project_summary_metricsdefault_response import InsightsGetProjectSummaryMetricsdefaultResponse as InsightsGetProjectSummaryMetricsdefaultResponseSchema
from circle_ci_python_sdk.model.insights_get_project_summary_metrics_response import InsightsGetProjectSummaryMetricsResponse as InsightsGetProjectSummaryMetricsResponseSchema

from circle_ci_python_sdk.type.insights_get_project_summary_metrics_response import InsightsGetProjectSummaryMetricsResponse
from circle_ci_python_sdk.type.insights_get_project_summary_metricsdefault_response import InsightsGetProjectSummaryMetricsdefaultResponse

from ...api_client import Dictionary
from circle_ci_python_sdk.pydantic.insights_get_project_summary_metrics_response import InsightsGetProjectSummaryMetricsResponse as InsightsGetProjectSummaryMetricsResponsePydantic
from circle_ci_python_sdk.pydantic.insights_get_project_summary_metricsdefault_response import InsightsGetProjectSummaryMetricsdefaultResponse as InsightsGetProjectSummaryMetricsdefaultResponsePydantic

from . import path

# Query params


class ReportingWindowSchema(
    schemas.EnumBase,
    schemas.StrSchema
):


    class MetaOapg:
        enum_value_to_name = {
            "last-7-days": "_7DAYS",
            "last-90-days": "_90DAYS",
            "last-24-hours": "_24HOURS",
            "last-30-days": "_30DAYS",
            "last-60-days": "_60DAYS",
        }
    
    @schemas.classproperty
    def _7DAYS(cls):
        return cls("last-7-days")
    
    @schemas.classproperty
    def _90DAYS(cls):
        return cls("last-90-days")
    
    @schemas.classproperty
    def _24HOURS(cls):
        return cls("last-24-hours")
    
    @schemas.classproperty
    def _30DAYS(cls):
        return cls("last-30-days")
    
    @schemas.classproperty
    def _60DAYS(cls):
        return cls("last-60-days")
BranchesSchema = schemas.DictSchema
WorkflowNamesSchema = schemas.DictSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'reporting-window': typing.Union[ReportingWindowSchema, str, ],
        'branches': typing.Union[BranchesSchema, dict, frozendict.frozendict, ],
        'workflow-names': typing.Union[WorkflowNamesSchema, dict, frozendict.frozendict, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_reporting_window = api_client.QueryParameter(
    name="reporting-window",
    style=api_client.ParameterStyle.FORM,
    schema=ReportingWindowSchema,
    explode=True,
)
request_query_branches = api_client.QueryParameter(
    name="branches",
    style=api_client.ParameterStyle.FORM,
    schema=BranchesSchema,
    explode=True,
)
request_query_workflow_names = api_client.QueryParameter(
    name="workflow-names",
    style=api_client.ParameterStyle.FORM,
    schema=WorkflowNamesSchema,
    explode=True,
)
# Path params
ProjectSlugSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'project-slug': typing.Union[ProjectSlugSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_project_slug = api_client.PathParameter(
    name="project-slug",
    style=api_client.ParameterStyle.SIMPLE,
    schema=ProjectSlugSchema,
    required=True,
)
_auth = [
    'api_key_header',
    'api_key_query',
    'basic_auth',
]
SchemaFor200ResponseBodyApplicationJson = InsightsGetProjectSummaryMetricsResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: InsightsGetProjectSummaryMetricsResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: InsightsGetProjectSummaryMetricsResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor0ResponseBodyApplicationJson = InsightsGetProjectSummaryMetricsdefaultResponseSchema


@dataclass
class ApiResponseForDefault(api_client.ApiResponse):
    body: InsightsGetProjectSummaryMetricsdefaultResponse


@dataclass
class ApiResponseForDefaultAsync(api_client.AsyncApiResponse):
    body: InsightsGetProjectSummaryMetricsdefaultResponse


_response_for_default = api_client.OpenApiResponse(
    response_cls=ApiResponseForDefault,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor0ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    'default': _response_for_default,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _get_project_summary_metrics_mapped_args(
        self,
        project_slug: str,
        reporting_window: typing.Optional[str] = None,
        branches: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        workflow_names: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _path_params = {}
        if reporting_window is not None:
            _query_params["reporting-window"] = reporting_window
        if branches is not None:
            _query_params["branches"] = branches
        if workflow_names is not None:
            _query_params["workflow-names"] = workflow_names
        if project_slug is not None:
            _path_params["project-slug"] = project_slug
        args.query = _query_params
        args.path = _path_params
        return args

    async def _aget_project_summary_metrics_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Get summary metrics and trends for a project across it&#x27;s workflows and branches
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_project_slug,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_reporting_window,
            request_query_branches,
            request_query_workflow_names,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/insights/pages/{project-slug}/summary',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserializationAsync(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_project_summary_metrics_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Get summary metrics and trends for a project across it&#x27;s workflows and branches
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_project_slug,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_reporting_window,
            request_query_branches,
            request_query_workflow_names,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/insights/pages/{project-slug}/summary',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetProjectSummaryMetricsRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_project_summary_metrics(
        self,
        project_slug: str,
        reporting_window: typing.Optional[str] = None,
        branches: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        workflow_names: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_project_summary_metrics_mapped_args(
            project_slug=project_slug,
            reporting_window=reporting_window,
            branches=branches,
            workflow_names=workflow_names,
        )
        return await self._aget_project_summary_metrics_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def get_project_summary_metrics(
        self,
        project_slug: str,
        reporting_window: typing.Optional[str] = None,
        branches: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        workflow_names: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_project_summary_metrics_mapped_args(
            project_slug=project_slug,
            reporting_window=reporting_window,
            branches=branches,
            workflow_names=workflow_names,
        )
        return self._get_project_summary_metrics_oapg(
            query_params=args.query,
            path_params=args.path,
        )

class GetProjectSummaryMetrics(BaseApi):

    async def aget_project_summary_metrics(
        self,
        project_slug: str,
        reporting_window: typing.Optional[str] = None,
        branches: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        workflow_names: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        validate: bool = False,
        **kwargs,
    ) -> InsightsGetProjectSummaryMetricsResponsePydantic:
        raw_response = await self.raw.aget_project_summary_metrics(
            project_slug=project_slug,
            reporting_window=reporting_window,
            branches=branches,
            workflow_names=workflow_names,
            **kwargs,
        )
        if validate:
            return InsightsGetProjectSummaryMetricsResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(InsightsGetProjectSummaryMetricsResponsePydantic, raw_response.body)
    
    
    def get_project_summary_metrics(
        self,
        project_slug: str,
        reporting_window: typing.Optional[str] = None,
        branches: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        workflow_names: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        validate: bool = False,
    ) -> InsightsGetProjectSummaryMetricsResponsePydantic:
        raw_response = self.raw.get_project_summary_metrics(
            project_slug=project_slug,
            reporting_window=reporting_window,
            branches=branches,
            workflow_names=workflow_names,
        )
        if validate:
            return InsightsGetProjectSummaryMetricsResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(InsightsGetProjectSummaryMetricsResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        project_slug: str,
        reporting_window: typing.Optional[str] = None,
        branches: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        workflow_names: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_project_summary_metrics_mapped_args(
            project_slug=project_slug,
            reporting_window=reporting_window,
            branches=branches,
            workflow_names=workflow_names,
        )
        return await self._aget_project_summary_metrics_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def get(
        self,
        project_slug: str,
        reporting_window: typing.Optional[str] = None,
        branches: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
        workflow_names: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_project_summary_metrics_mapped_args(
            project_slug=project_slug,
            reporting_window=reporting_window,
            branches=branches,
            workflow_names=workflow_names,
        )
        return self._get_project_summary_metrics_oapg(
            query_params=args.query,
            path_params=args.path,
        )

