# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from circle_ci_python_sdk.paths.context.post import CreateNewContextRaw
from circle_ci_python_sdk.paths.context_context_id_restrictions.post import CreateRestrictionRaw
from circle_ci_python_sdk.paths.context_context_id_restrictions_restriction_id.delete import DeleteRestrictionRaw
from circle_ci_python_sdk.paths.context_context_id.get import GetInformationRaw
from circle_ci_python_sdk.paths.context_context_id_restrictions.get import GetRestrictionsRaw
from circle_ci_python_sdk.paths.context_context_id_environment_variable.get import ListEnvironmentVariablesRaw
from circle_ci_python_sdk.paths.context.get import ListOwnerContextsRaw
from circle_ci_python_sdk.paths.context_context_id.delete import RemoveContextRaw
from circle_ci_python_sdk.paths.context_context_id_environment_variable_env_var_name.delete import RemoveEnvironmentVariableRaw
from circle_ci_python_sdk.paths.context_context_id_environment_variable_env_var_name.put import UpdateEnvironmentVariableRaw


class ContextApiRaw(
    CreateNewContextRaw,
    CreateRestrictionRaw,
    DeleteRestrictionRaw,
    GetInformationRaw,
    GetRestrictionsRaw,
    ListEnvironmentVariablesRaw,
    ListOwnerContextsRaw,
    RemoveContextRaw,
    RemoveEnvironmentVariableRaw,
    UpdateEnvironmentVariableRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
