# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from circle_ci_python_sdk.paths.insights_project_slug_flaky_tests.get import GetFlakyTests
from circle_ci_python_sdk.paths.insights_time_series_project_slug_workflows_workflow_name_jobs.get import GetJobTimeseriesData
from circle_ci_python_sdk.paths.insights_pages_project_slug_summary.get import GetProjectSummaryMetrics
from circle_ci_python_sdk.paths.insights_project_slug_workflows_workflow_name_jobs.get import GetProjectWorkflowJobMetrics
from circle_ci_python_sdk.paths.insights_project_slug_workflows.get import GetProjectWorkflowMetrics
from circle_ci_python_sdk.paths.insights_project_slug_workflows_workflow_name_test_metrics.get import GetProjectWorkflowTestMetrics
from circle_ci_python_sdk.paths.insights_project_slug_workflows_workflow_name.get import GetRecentWorkflowRuns
from circle_ci_python_sdk.paths.insights_org_slug_summary.get import GetSummaryMetricsWithTrends
from circle_ci_python_sdk.paths.insights_project_slug_workflows_workflow_name_summary.get import GetWorkflowSummaryMetrics
from circle_ci_python_sdk.paths.insights_project_slug_branches.get import ListProjectBranches
from circle_ci_python_sdk.apis.tags.insights_api_raw import InsightsApiRaw


class InsightsApi(
    GetFlakyTests,
    GetJobTimeseriesData,
    GetProjectSummaryMetrics,
    GetProjectWorkflowJobMetrics,
    GetProjectWorkflowMetrics,
    GetProjectWorkflowTestMetrics,
    GetRecentWorkflowRuns,
    GetSummaryMetricsWithTrends,
    GetWorkflowSummaryMetrics,
    ListProjectBranches,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: InsightsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = InsightsApiRaw(api_client)
