# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from circle_ci_python_sdk.paths.project_project_slug_job_job_number_cancel.post import CancelWithNumber
from circle_ci_python_sdk.paths.project_project_slug_job_number_artifacts.get import GetArtifacts
from circle_ci_python_sdk.paths.project_project_slug_job_job_number.get import GetDetails
from circle_ci_python_sdk.paths.project_project_slug_job_number_tests.get import GetTestMetadata
from circle_ci_python_sdk.apis.tags.job_api_raw import JobApiRaw


class JobApi(
    CancelWithNumber,
    GetArtifacts,
    GetDetails,
    GetTestMetadata,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: JobApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = JobApiRaw(api_client)
