# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from circle_ci_python_sdk.paths.org_org_id_oidc_custom_claims.delete import DeleteOrgClaims
from circle_ci_python_sdk.paths.org_org_id_project_project_id_oidc_custom_claims.delete import DeleteProjectClaims
from circle_ci_python_sdk.paths.org_org_id_oidc_custom_claims.get import GetOrgClaims
from circle_ci_python_sdk.paths.org_org_id_project_project_id_oidc_custom_claims.get import GetProjectClaims
from circle_ci_python_sdk.paths.org_org_id_oidc_custom_claims.patch import UpdateOrgClaims
from circle_ci_python_sdk.paths.org_org_id_project_project_id_oidc_custom_claims.patch import UpdateProjectClaims
from circle_ci_python_sdk.apis.tags.oidc_token_management_api_raw import OIDCTokenManagementApiRaw


class OIDCTokenManagementApi(
    DeleteOrgClaims,
    DeleteProjectClaims,
    GetOrgClaims,
    GetProjectClaims,
    UpdateOrgClaims,
    UpdateProjectClaims,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: OIDCTokenManagementApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = OIDCTokenManagementApiRaw(api_client)
