# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from circle_ci_python_sdk.paths.pipeline_continue.post import ContinueExecutionRaw
from circle_ci_python_sdk.paths.project_project_slug_pipeline.get import GetAllPipelinesRaw
from circle_ci_python_sdk.paths.pipeline_pipeline_id.get import GetByIdRaw
from circle_ci_python_sdk.paths.project_project_slug_pipeline_pipeline_number.get import GetByNumberRaw
from circle_ci_python_sdk.paths.pipeline_pipeline_id_config.get import GetConfigurationByIdRaw
from circle_ci_python_sdk.paths.pipeline.get import ListRecentPipelinesRaw
from circle_ci_python_sdk.paths.project_project_slug_pipeline_mine.get import ListUserPipelinesRaw
from circle_ci_python_sdk.paths.pipeline_pipeline_id_workflow.get import ListWorkflowsRaw
from circle_ci_python_sdk.paths.project_project_slug_pipeline.post import TriggerNewPipelineRaw


class PipelineApiRaw(
    ContinueExecutionRaw,
    GetAllPipelinesRaw,
    GetByIdRaw,
    GetByNumberRaw,
    GetConfigurationByIdRaw,
    ListRecentPipelinesRaw,
    ListUserPipelinesRaw,
    ListWorkflowsRaw,
    TriggerNewPipelineRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
