# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from circle_ci_python_sdk.paths.webhook.post import CreateOutboundWebhookRaw
from circle_ci_python_sdk.paths.webhook_webhook_id.delete import DeleteOutboundWebhookRaw
from circle_ci_python_sdk.paths.webhook_webhook_id.get import GetByIdRaw
from circle_ci_python_sdk.paths.webhook.get import ListMatchingScopeRaw
from circle_ci_python_sdk.paths.webhook_webhook_id.put import UpdateOutboundWebhookRaw


class WebhookApiRaw(
    CreateOutboundWebhookRaw,
    DeleteOutboundWebhookRaw,
    GetByIdRaw,
    ListMatchingScopeRaw,
    UpdateOutboundWebhookRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
