# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from circle_ci_python_sdk.paths.workflow_id_approve_approval_request_id.post import ApproveJob
from circle_ci_python_sdk.paths.workflow_id_cancel.post import CancelWorkflow
from circle_ci_python_sdk.paths.workflow_id.get import GetById
from circle_ci_python_sdk.paths.workflow_id_job.get import GetJobs
from circle_ci_python_sdk.paths.workflow_id_rerun.post import RerunWorkflow
from circle_ci_python_sdk.apis.tags.workflow_api_raw import WorkflowApiRaw


class WorkflowApi(
    ApproveJob,
    CancelWorkflow,
    GetById,
    GetJobs,
    RerunWorkflow,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WorkflowApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WorkflowApiRaw(api_client)
