# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from circle_ci_python_sdk.paths.workflow_id_approve_approval_request_id.post import ApproveJobRaw
from circle_ci_python_sdk.paths.workflow_id_cancel.post import CancelWorkflowRaw
from circle_ci_python_sdk.paths.workflow_id.get import GetByIdRaw
from circle_ci_python_sdk.paths.workflow_id_job.get import GetJobsRaw
from circle_ci_python_sdk.paths.workflow_id_rerun.post import RerunWorkflowRaw


class WorkflowApiRaw(
    ApproveJobRaw,
    CancelWorkflowRaw,
    GetByIdRaw,
    GetJobsRaw,
    RerunWorkflowRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
