# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from circle_ci_python_sdk.type.context_project_restrictions_list_items import ContextProjectRestrictionsListItems

class RequiredContextProjectRestrictionsList(TypedDict):
    pass

class OptionalContextProjectRestrictionsList(TypedDict, total=False):
    items: ContextProjectRestrictionsListItems

    # Token that can be used to retrieve next page of results
    next_page_token: typing.Optional[str]

class ContextProjectRestrictionsList(RequiredContextProjectRestrictionsList, OptionalContextProjectRestrictionsList):
    pass
