# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from circle_ci_python_sdk.type.insights_get_project_summary_metrics_response_project_workflow_data_item_metrics import InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataItemMetrics
from circle_ci_python_sdk.type.insights_get_project_summary_metrics_response_project_workflow_data_item_trends import InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataItemTrends

class RequiredInsightsGetProjectSummaryMetricsResponseProjectWorkflowDataItem(TypedDict):
    # The name of the workflow.
    workflow_name: str

    metrics: InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataItemMetrics

    trends: InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataItemTrends

class OptionalInsightsGetProjectSummaryMetricsResponseProjectWorkflowDataItem(TypedDict, total=False):
    pass

class InsightsGetProjectSummaryMetricsResponseProjectWorkflowDataItem(RequiredInsightsGetProjectSummaryMetricsResponseProjectWorkflowDataItem, OptionalInsightsGetProjectSummaryMetricsResponseProjectWorkflowDataItem):
    pass
