# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from circle_ci_python_sdk.type.insights_get_project_workflow_metrics_response_items_item_metrics_duration_metrics import InsightsGetProjectWorkflowMetricsResponseItemsItemMetricsDurationMetrics

class RequiredInsightsGetProjectWorkflowMetricsResponseItemsItemMetrics(TypedDict):
    # The total number of runs, including runs that are still on-hold or running.
    total_runs: int

    # The number of successful runs.
    successful_runs: int

    # The mean time to recovery (mean time between failures and their next success) in seconds.
    mttr: typing.Optional[int]

    # The total credits consumed by the workflow in the aggregation window. Note that Insights is not a real time financial reporting tool and should not be used for credit reporting.
    total_credits_used: typing.Optional[int]

    # The number of failed runs.
    failed_runs: int

    success_rate: typing.Union[int, float]

    duration_metrics: InsightsGetProjectWorkflowMetricsResponseItemsItemMetricsDurationMetrics

    # The number of recovered workflow executions per day.
    total_recoveries: typing.Optional[int]

    # The average number of runs per day.
    throughput: typing.Union[int, float]

class OptionalInsightsGetProjectWorkflowMetricsResponseItemsItemMetrics(TypedDict, total=False):
    pass

class InsightsGetProjectWorkflowMetricsResponseItemsItemMetrics(RequiredInsightsGetProjectWorkflowMetricsResponseItemsItemMetrics, OptionalInsightsGetProjectWorkflowMetricsResponseItemsItemMetrics):
    pass
