# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from circle_ci_python_sdk.type.insights_get_workflow_summary_metrics_response_metrics import InsightsGetWorkflowSummaryMetricsResponseMetrics
from circle_ci_python_sdk.type.insights_get_workflow_summary_metrics_response_trends import InsightsGetWorkflowSummaryMetricsResponseTrends
from circle_ci_python_sdk.type.insights_get_workflow_summary_metrics_response_workflow_names import InsightsGetWorkflowSummaryMetricsResponseWorkflowNames

class RequiredInsightsGetWorkflowSummaryMetricsResponse(TypedDict):
    metrics: InsightsGetWorkflowSummaryMetricsResponseMetrics

    trends: InsightsGetWorkflowSummaryMetricsResponseTrends

    workflow_names: InsightsGetWorkflowSummaryMetricsResponseWorkflowNames

class OptionalInsightsGetWorkflowSummaryMetricsResponse(TypedDict, total=False):
    pass

class InsightsGetWorkflowSummaryMetricsResponse(RequiredInsightsGetWorkflowSummaryMetricsResponse, OptionalInsightsGetWorkflowSummaryMetricsResponse):
    pass
