# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from circle_ci_python_sdk.type.insights_get_summary_metrics_with_trends_response_org_project_data_item_metrics import InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataItemMetrics
from circle_ci_python_sdk.type.insights_get_summary_metrics_with_trends_response_org_project_data_item_trends import InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataItemTrends

class RequiredInsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataItem(TypedDict):
    # The name of the project.
    project_name: str

    metrics: InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataItemMetrics

    trends: InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataItemTrends

class OptionalInsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataItem(TypedDict, total=False):
    pass

class InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataItem(RequiredInsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataItem, OptionalInsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataItem):
    pass
