# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredJobGetDetailsResponseMessagesItem(TypedDict):
    # Message type.
    type: str

    # Information describing message.
    message: str

class OptionalJobGetDetailsResponseMessagesItem(TypedDict, total=False):
    # Value describing the reason for message to be added to the job.
    reason: str

class JobGetDetailsResponseMessagesItem(RequiredJobGetDetailsResponseMessagesItem, OptionalJobGetDetailsResponseMessagesItem):
    pass
