# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredPipelineListUserPipelinesResponseItemsItemTriggerActor(TypedDict):
    # The login information for the user on the VCS.
    login: str

    # URL to the user's avatar on the VCS
    avatar_url: typing.Optional[str]

class OptionalPipelineListUserPipelinesResponseItemsItemTriggerActor(TypedDict, total=False):
    pass

class PipelineListUserPipelinesResponseItemsItemTriggerActor(RequiredPipelineListUserPipelinesResponseItemsItemTriggerActor, OptionalPipelineListUserPipelinesResponseItemsItemTriggerActor):
    pass
