# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from circle_ci_python_sdk.type.project_get_by_slug_response_vcs_info import ProjectGetBySlugResponseVcsInfo

class RequiredProjectGetBySlugResponse(TypedDict):
    # Project slug in the form `vcs-slug/org-name/repo-name`. The `/` characters may be URL-escaped. For projects that use GitLab or GitHub App, use `circleci` as the `vcs-slug`, replace `org-name` with the organization ID (found in Organization Settings), and replace `repo-name` with the project ID (found in Project Settings).
    slug: str

    # The name of the project
    name: str

    id: str

    # The name of the organization the project belongs to
    organization_name: str

    # The slug of the organization the project belongs to
    organization_slug: str

    # The id of the organization the project belongs to
    organization_id: str

    vcs_info: ProjectGetBySlugResponseVcsInfo

class OptionalProjectGetBySlugResponse(TypedDict, total=False):
    pass

class ProjectGetBySlugResponse(RequiredProjectGetBySlugResponse, OptionalProjectGetBySlugResponse):
    pass
