# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


RequiredProjectGetMaskedEnvVarResponse = TypedDict("RequiredProjectGetMaskedEnvVarResponse", {
    # The name of the environment variable.
    "name": str,

    # The value of the environment variable.
    "value": str,
    })

OptionalProjectGetMaskedEnvVarResponse = TypedDict("OptionalProjectGetMaskedEnvVarResponse", {
    # The creation timestamp of the environment variable.
    "created-at": typing.Union[bool, date, datetime, dict, float, int, list, str, None],
    }, total=False)

class ProjectGetMaskedEnvVarResponse(RequiredProjectGetMaskedEnvVarResponse, OptionalProjectGetMaskedEnvVarResponse):
    pass
