# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredProjectCreateEnvVarRequest(TypedDict):
    # The name of the environment variable.
    name: str

    # The value of the environment variable.
    value: str

class OptionalProjectCreateEnvVarRequest(TypedDict, total=False):
    pass

class ProjectCreateEnvVarRequest(RequiredProjectCreateEnvVarRequest, OptionalProjectCreateEnvVarRequest):
    pass
