# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


RequiredUserListCollaborationsResponseItem = TypedDict("RequiredUserListCollaborationsResponseItem", {
    # The UUID of the organization
    "id": typing.Optional[str],

    # The VCS provider
    "vcs-type": str,

    # The name of the organization
    "name": str,

    # URL to the user's avatar on the VCS
    "avatar_url": str,

    # The slug of the organization
    "slug": str,
    })

OptionalUserListCollaborationsResponseItem = TypedDict("OptionalUserListCollaborationsResponseItem", {
    }, total=False)

class UserListCollaborationsResponseItem(RequiredUserListCollaborationsResponseItem, OptionalUserListCollaborationsResponseItem):
    pass
