# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from circle_ci_python_sdk.type.webhook_update_outbound_webhook_request_events import WebhookUpdateOutboundWebhookRequestEvents

RequiredWebhookUpdateOutboundWebhookRequest = TypedDict("RequiredWebhookUpdateOutboundWebhookRequest", {
    })

OptionalWebhookUpdateOutboundWebhookRequest = TypedDict("OptionalWebhookUpdateOutboundWebhookRequest", {
    # Name of the webhook
    "name": str,

    "events": WebhookUpdateOutboundWebhookRequestEvents,

    # URL to deliver the webhook to. Note: protocol must be included as well (only https is supported)
    "url": str,

    # Secret used to build an HMAC hash of the payload and passed as a header in the webhook request
    "signing-secret": str,

    # Whether to enforce TLS certificate verification when delivering the webhook
    "verify-tls": bool,
    }, total=False)

class WebhookUpdateOutboundWebhookRequest(RequiredWebhookUpdateOutboundWebhookRequest, OptionalWebhookUpdateOutboundWebhookRequest):
    pass
