# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from circle_ci_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from circle_ci_python_sdk.api_response import AsyncGeneratorResponse
from circle_ci_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from circle_ci_python_sdk import schemas  # noqa: F401

from circle_ci_python_sdk.model.job_cancel_with_numberdefault_response import JobCancelWithNumberdefaultResponse as JobCancelWithNumberdefaultResponseSchema
from circle_ci_python_sdk.model.job_cancel_with_number_response import JobCancelWithNumberResponse as JobCancelWithNumberResponseSchema

from circle_ci_python_sdk.type.job_cancel_with_numberdefault_response import JobCancelWithNumberdefaultResponse
from circle_ci_python_sdk.type.job_cancel_with_number_response import JobCancelWithNumberResponse

from ...api_client import Dictionary
from circle_ci_python_sdk.pydantic.job_cancel_with_numberdefault_response import JobCancelWithNumberdefaultResponse as JobCancelWithNumberdefaultResponsePydantic
from circle_ci_python_sdk.pydantic.job_cancel_with_number_response import JobCancelWithNumberResponse as JobCancelWithNumberResponsePydantic

from . import path

# Path params
JobNumberSchema = schemas.AnyTypeSchema
ProjectSlugSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'job-number': typing.Union[JobNumberSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, bool, None, list, tuple, bytes, io.FileIO, io.BufferedReader, ],
        'project-slug': typing.Union[ProjectSlugSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_job_number = api_client.PathParameter(
    name="job-number",
    style=api_client.ParameterStyle.SIMPLE,
    schema=JobNumberSchema,
    required=True,
)
request_path_project_slug = api_client.PathParameter(
    name="project-slug",
    style=api_client.ParameterStyle.SIMPLE,
    schema=ProjectSlugSchema,
    required=True,
)
_auth = [
    'api_key_header',
    'api_key_query',
    'basic_auth',
]
SchemaFor200ResponseBodyApplicationJson = JobCancelWithNumberResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: JobCancelWithNumberResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: JobCancelWithNumberResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor0ResponseBodyApplicationJson = JobCancelWithNumberdefaultResponseSchema


@dataclass
class ApiResponseForDefault(api_client.ApiResponse):
    body: JobCancelWithNumberdefaultResponse


@dataclass
class ApiResponseForDefaultAsync(api_client.AsyncApiResponse):
    body: JobCancelWithNumberdefaultResponse


_response_for_default = api_client.OpenApiResponse(
    response_cls=ApiResponseForDefault,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor0ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    'default': _response_for_default,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _cancel_with_number_mapped_args(
        self,
        job_number: typing.Union[bool, date, datetime, dict, float, int, list, str, None],
        project_slug: str,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _path_params = {}
        if job_number is not None:
            _path_params["job-number"] = job_number
        if project_slug is not None:
            _path_params["project-slug"] = project_slug
        args.path = _path_params
        return args

    async def _acancel_with_number_oapg(
        self,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Cancel job
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_job_number,
            request_path_project_slug,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/project/{project-slug}/job/{job-number}/cancel',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserializationAsync(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _cancel_with_number_oapg(
        self,
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Cancel job
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_job_number,
            request_path_project_slug,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/project/{project-slug}/job/{job-number}/cancel',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            default_response = _status_code_to_response.get('default')
            if default_response:
                api_response = default_response.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
            else:
                api_response = api_client.ApiResponseWithoutDeserialization(
                    response=response.http_response,
                    round_trip_time=response.round_trip_time,
                    status=response.http_response.status,
                    headers=response.http_response.headers,
                )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class CancelWithNumberRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def acancel_with_number(
        self,
        job_number: typing.Union[bool, date, datetime, dict, float, int, list, str, None],
        project_slug: str,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._cancel_with_number_mapped_args(
            job_number=job_number,
            project_slug=project_slug,
        )
        return await self._acancel_with_number_oapg(
            path_params=args.path,
            **kwargs,
        )
    
    def cancel_with_number(
        self,
        job_number: typing.Union[bool, date, datetime, dict, float, int, list, str, None],
        project_slug: str,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._cancel_with_number_mapped_args(
            job_number=job_number,
            project_slug=project_slug,
        )
        return self._cancel_with_number_oapg(
            path_params=args.path,
        )

class CancelWithNumber(BaseApi):

    async def acancel_with_number(
        self,
        job_number: typing.Union[bool, date, datetime, dict, float, int, list, str, None],
        project_slug: str,
        validate: bool = False,
        **kwargs,
    ) -> JobCancelWithNumberResponsePydantic:
        raw_response = await self.raw.acancel_with_number(
            job_number=job_number,
            project_slug=project_slug,
            **kwargs,
        )
        if validate:
            return JobCancelWithNumberResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(JobCancelWithNumberResponsePydantic, raw_response.body)
    
    
    def cancel_with_number(
        self,
        job_number: typing.Union[bool, date, datetime, dict, float, int, list, str, None],
        project_slug: str,
        validate: bool = False,
    ) -> JobCancelWithNumberResponsePydantic:
        raw_response = self.raw.cancel_with_number(
            job_number=job_number,
            project_slug=project_slug,
        )
        if validate:
            return JobCancelWithNumberResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(JobCancelWithNumberResponsePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        job_number: typing.Union[bool, date, datetime, dict, float, int, list, str, None],
        project_slug: str,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        ApiResponseForDefaultAsync,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._cancel_with_number_mapped_args(
            job_number=job_number,
            project_slug=project_slug,
        )
        return await self._acancel_with_number_oapg(
            path_params=args.path,
            **kwargs,
        )
    
    def post(
        self,
        job_number: typing.Union[bool, date, datetime, dict, float, int, list, str, None],
        project_slug: str,
    ) -> typing.Union[
        ApiResponseFor200,
        ApiResponseForDefault,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._cancel_with_number_mapped_args(
            job_number=job_number,
            project_slug=project_slug,
        )
        return self._cancel_with_number_oapg(
            path_params=args.path,
        )

