# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from circle_ci_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from circle_ci_python_sdk.api_response import AsyncGeneratorResponse
from circle_ci_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from circle_ci_python_sdk import schemas  # noqa: F401

from circle_ci_python_sdk.model.oidc_token_management_delete_org_claims_response import OidcTokenManagementDeleteOrgClaimsResponse as OidcTokenManagementDeleteOrgClaimsResponseSchema
from circle_ci_python_sdk.model.policy_management_get_decision_audit_logs500_response import PolicyManagementGetDecisionAuditLogs500Response as PolicyManagementGetDecisionAuditLogs500ResponseSchema
from circle_ci_python_sdk.model.policy_management_get_decision_audit_logs401_response import PolicyManagementGetDecisionAuditLogs401Response as PolicyManagementGetDecisionAuditLogs401ResponseSchema
from circle_ci_python_sdk.model.policy_management_get_decision_audit_logs_response import PolicyManagementGetDecisionAuditLogsResponse as PolicyManagementGetDecisionAuditLogsResponseSchema
from circle_ci_python_sdk.model.oidc_token_management_delete_org_claims403_response import OidcTokenManagementDeleteOrgClaims403Response as OidcTokenManagementDeleteOrgClaims403ResponseSchema

from circle_ci_python_sdk.type.policy_management_get_decision_audit_logs500_response import PolicyManagementGetDecisionAuditLogs500Response
from circle_ci_python_sdk.type.oidc_token_management_delete_org_claims_response import OidcTokenManagementDeleteOrgClaimsResponse
from circle_ci_python_sdk.type.policy_management_get_decision_audit_logs_response import PolicyManagementGetDecisionAuditLogsResponse
from circle_ci_python_sdk.type.oidc_token_management_delete_org_claims403_response import OidcTokenManagementDeleteOrgClaims403Response
from circle_ci_python_sdk.type.policy_management_get_decision_audit_logs401_response import PolicyManagementGetDecisionAuditLogs401Response

from ...api_client import Dictionary
from circle_ci_python_sdk.pydantic.policy_management_get_decision_audit_logs401_response import PolicyManagementGetDecisionAuditLogs401Response as PolicyManagementGetDecisionAuditLogs401ResponsePydantic
from circle_ci_python_sdk.pydantic.oidc_token_management_delete_org_claims403_response import OidcTokenManagementDeleteOrgClaims403Response as OidcTokenManagementDeleteOrgClaims403ResponsePydantic
from circle_ci_python_sdk.pydantic.policy_management_get_decision_audit_logs500_response import PolicyManagementGetDecisionAuditLogs500Response as PolicyManagementGetDecisionAuditLogs500ResponsePydantic
from circle_ci_python_sdk.pydantic.policy_management_get_decision_audit_logs_response import PolicyManagementGetDecisionAuditLogsResponse as PolicyManagementGetDecisionAuditLogsResponsePydantic
from circle_ci_python_sdk.pydantic.oidc_token_management_delete_org_claims_response import OidcTokenManagementDeleteOrgClaimsResponse as OidcTokenManagementDeleteOrgClaimsResponsePydantic

# Query params
StatusSchema = schemas.StrSchema
AfterSchema = schemas.DateTimeSchema
BeforeSchema = schemas.DateTimeSchema
BranchSchema = schemas.StrSchema
ProjectIdSchema = schemas.StrSchema
BuildNumberSchema = schemas.StrSchema
OffsetSchema = schemas.IntSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'status': typing.Union[StatusSchema, str, ],
        'after': typing.Union[AfterSchema, str, datetime, ],
        'before': typing.Union[BeforeSchema, str, datetime, ],
        'branch': typing.Union[BranchSchema, str, ],
        'project_id': typing.Union[ProjectIdSchema, str, ],
        'build_number': typing.Union[BuildNumberSchema, str, ],
        'offset': typing.Union[OffsetSchema, decimal.Decimal, int, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_status = api_client.QueryParameter(
    name="status",
    style=api_client.ParameterStyle.FORM,
    schema=StatusSchema,
    explode=True,
)
request_query_after = api_client.QueryParameter(
    name="after",
    style=api_client.ParameterStyle.FORM,
    schema=AfterSchema,
    explode=True,
)
request_query_before = api_client.QueryParameter(
    name="before",
    style=api_client.ParameterStyle.FORM,
    schema=BeforeSchema,
    explode=True,
)
request_query_branch = api_client.QueryParameter(
    name="branch",
    style=api_client.ParameterStyle.FORM,
    schema=BranchSchema,
    explode=True,
)
request_query_project_id = api_client.QueryParameter(
    name="project_id",
    style=api_client.ParameterStyle.FORM,
    schema=ProjectIdSchema,
    explode=True,
)
request_query_build_number = api_client.QueryParameter(
    name="build_number",
    style=api_client.ParameterStyle.FORM,
    schema=BuildNumberSchema,
    explode=True,
)
request_query_offset = api_client.QueryParameter(
    name="offset",
    style=api_client.ParameterStyle.FORM,
    schema=OffsetSchema,
    explode=True,
)
# Path params
OwnerIDSchema = schemas.StrSchema
ContextSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'ownerID': typing.Union[OwnerIDSchema, str, ],
        'context': typing.Union[ContextSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_owner_id = api_client.PathParameter(
    name="ownerID",
    style=api_client.ParameterStyle.SIMPLE,
    schema=OwnerIDSchema,
    required=True,
)
request_path_context = api_client.PathParameter(
    name="context",
    style=api_client.ParameterStyle.SIMPLE,
    schema=ContextSchema,
    required=True,
)
SchemaFor200ResponseBodyApplicationJson = PolicyManagementGetDecisionAuditLogsResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: PolicyManagementGetDecisionAuditLogsResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: PolicyManagementGetDecisionAuditLogsResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor400ResponseBodyApplicationJson = OidcTokenManagementDeleteOrgClaimsResponseSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: OidcTokenManagementDeleteOrgClaimsResponse


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: OidcTokenManagementDeleteOrgClaimsResponse


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
SchemaFor401ResponseBodyApplicationJson = PolicyManagementGetDecisionAuditLogs401ResponseSchema


@dataclass
class ApiResponseFor401(api_client.ApiResponse):
    body: PolicyManagementGetDecisionAuditLogs401Response


@dataclass
class ApiResponseFor401Async(api_client.AsyncApiResponse):
    body: PolicyManagementGetDecisionAuditLogs401Response


_response_for_401 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor401,
    response_cls_async=ApiResponseFor401Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor401ResponseBodyApplicationJson),
    },
)
SchemaFor403ResponseBodyApplicationJson = OidcTokenManagementDeleteOrgClaims403ResponseSchema


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: OidcTokenManagementDeleteOrgClaims403Response


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: OidcTokenManagementDeleteOrgClaims403Response


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationJson),
    },
)
SchemaFor500ResponseBodyApplicationJson = PolicyManagementGetDecisionAuditLogs500ResponseSchema


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: PolicyManagementGetDecisionAuditLogs500Response


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: PolicyManagementGetDecisionAuditLogs500Response


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _get_decision_audit_logs_mapped_args(
        self,
        owner_id: str,
        context: str,
        status: typing.Optional[str] = None,
        after: typing.Optional[datetime] = None,
        before: typing.Optional[datetime] = None,
        branch: typing.Optional[str] = None,
        project_id: typing.Optional[str] = None,
        build_number: typing.Optional[str] = None,
        offset: typing.Optional[int] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _path_params = {}
        if status is not None:
            _query_params["status"] = status
        if after is not None:
            _query_params["after"] = after
        if before is not None:
            _query_params["before"] = before
        if branch is not None:
            _query_params["branch"] = branch
        if project_id is not None:
            _query_params["project_id"] = project_id
        if build_number is not None:
            _query_params["build_number"] = build_number
        if offset is not None:
            _query_params["offset"] = offset
        if owner_id is not None:
            _path_params["ownerID"] = owner_id
        if context is not None:
            _path_params["context"] = context
        args.query = _query_params
        args.path = _path_params
        return args

    async def _aget_decision_audit_logs_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Retrieves the owner&#x27;s decision audit logs.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_owner_id,
            request_path_context,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_status,
            request_query_after,
            request_query_before,
            request_query_branch,
            request_query_project_id,
            request_query_build_number,
            request_query_offset,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/owner/{ownerID}/context/{context}/decision',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _get_decision_audit_logs_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Retrieves the owner&#x27;s decision audit logs.
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_owner_id,
            request_path_context,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_status,
            request_query_after,
            request_query_before,
            request_query_branch,
            request_query_project_id,
            request_query_build_number,
            request_query_offset,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/owner/{ownerID}/context/{context}/decision',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class GetDecisionAuditLogsRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def aget_decision_audit_logs(
        self,
        owner_id: str,
        context: str,
        status: typing.Optional[str] = None,
        after: typing.Optional[datetime] = None,
        before: typing.Optional[datetime] = None,
        branch: typing.Optional[str] = None,
        project_id: typing.Optional[str] = None,
        build_number: typing.Optional[str] = None,
        offset: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_decision_audit_logs_mapped_args(
            owner_id=owner_id,
            context=context,
            status=status,
            after=after,
            before=before,
            branch=branch,
            project_id=project_id,
            build_number=build_number,
            offset=offset,
        )
        return await self._aget_decision_audit_logs_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def get_decision_audit_logs(
        self,
        owner_id: str,
        context: str,
        status: typing.Optional[str] = None,
        after: typing.Optional[datetime] = None,
        before: typing.Optional[datetime] = None,
        branch: typing.Optional[str] = None,
        project_id: typing.Optional[str] = None,
        build_number: typing.Optional[str] = None,
        offset: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_decision_audit_logs_mapped_args(
            owner_id=owner_id,
            context=context,
            status=status,
            after=after,
            before=before,
            branch=branch,
            project_id=project_id,
            build_number=build_number,
            offset=offset,
        )
        return self._get_decision_audit_logs_oapg(
            query_params=args.query,
            path_params=args.path,
        )

class GetDecisionAuditLogs(BaseApi):

    async def aget_decision_audit_logs(
        self,
        owner_id: str,
        context: str,
        status: typing.Optional[str] = None,
        after: typing.Optional[datetime] = None,
        before: typing.Optional[datetime] = None,
        branch: typing.Optional[str] = None,
        project_id: typing.Optional[str] = None,
        build_number: typing.Optional[str] = None,
        offset: typing.Optional[int] = None,
        validate: bool = False,
        **kwargs,
    ) -> PolicyManagementGetDecisionAuditLogsResponsePydantic:
        raw_response = await self.raw.aget_decision_audit_logs(
            owner_id=owner_id,
            context=context,
            status=status,
            after=after,
            before=before,
            branch=branch,
            project_id=project_id,
            build_number=build_number,
            offset=offset,
            **kwargs,
        )
        if validate:
            return RootModel[PolicyManagementGetDecisionAuditLogsResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(PolicyManagementGetDecisionAuditLogsResponsePydantic, raw_response.body)
    
    
    def get_decision_audit_logs(
        self,
        owner_id: str,
        context: str,
        status: typing.Optional[str] = None,
        after: typing.Optional[datetime] = None,
        before: typing.Optional[datetime] = None,
        branch: typing.Optional[str] = None,
        project_id: typing.Optional[str] = None,
        build_number: typing.Optional[str] = None,
        offset: typing.Optional[int] = None,
        validate: bool = False,
    ) -> PolicyManagementGetDecisionAuditLogsResponsePydantic:
        raw_response = self.raw.get_decision_audit_logs(
            owner_id=owner_id,
            context=context,
            status=status,
            after=after,
            before=before,
            branch=branch,
            project_id=project_id,
            build_number=build_number,
            offset=offset,
        )
        if validate:
            return RootModel[PolicyManagementGetDecisionAuditLogsResponsePydantic](raw_response.body).root
        return api_client.construct_model_instance(PolicyManagementGetDecisionAuditLogsResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        owner_id: str,
        context: str,
        status: typing.Optional[str] = None,
        after: typing.Optional[datetime] = None,
        before: typing.Optional[datetime] = None,
        branch: typing.Optional[str] = None,
        project_id: typing.Optional[str] = None,
        build_number: typing.Optional[str] = None,
        offset: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._get_decision_audit_logs_mapped_args(
            owner_id=owner_id,
            context=context,
            status=status,
            after=after,
            before=before,
            branch=branch,
            project_id=project_id,
            build_number=build_number,
            offset=offset,
        )
        return await self._aget_decision_audit_logs_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def get(
        self,
        owner_id: str,
        context: str,
        status: typing.Optional[str] = None,
        after: typing.Optional[datetime] = None,
        before: typing.Optional[datetime] = None,
        branch: typing.Optional[str] = None,
        project_id: typing.Optional[str] = None,
        build_number: typing.Optional[str] = None,
        offset: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._get_decision_audit_logs_mapped_args(
            owner_id=owner_id,
            context=context,
            status=status,
            after=after,
            before=before,
            branch=branch,
            project_id=project_id,
            build_number=build_number,
            offset=offset,
        )
        return self._get_decision_audit_logs_oapg(
            query_params=args.query,
            path_params=args.path,
        )

