# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from circle_ci_python_sdk.pydantic.bundle_diff_created import BundleDiffCreated
from circle_ci_python_sdk.pydantic.bundle_diff_deleted import BundleDiffDeleted
from circle_ci_python_sdk.pydantic.bundle_diff_modified import BundleDiffModified

class BundleDiff(BaseModel):
    created: typing.Optional[BundleDiffCreated] = Field(None, alias='created')

    deleted: typing.Optional[BundleDiffDeleted] = Field(None, alias='deleted')

    modified: typing.Optional[BundleDiffModified] = Field(None, alias='modified')
    class Config:
        arbitrary_types_allowed = True
