# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ContextListEnvironmentVariablesResponseItemsItem(BaseModel):
    # The name of the environment variable
    variable: str = Field(alias='variable')

    # The date and time the environment variable was created.
    created_at: datetime = Field(alias='created_at')

    # The date and time the environment variable was updated
    updated_at: datetime = Field(alias='updated_at')

    # ID of the context (UUID)
    context_id: str = Field(alias='context_id')
    class Config:
        arbitrary_types_allowed = True
