# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from circle_ci_python_sdk.pydantic.decision import Decision
from circle_ci_python_sdk.pydantic.decision_log_metadata import DecisionLogMetadata
from circle_ci_python_sdk.pydantic.decision_log_policies import DecisionLogPolicies

class DecisionLog(BaseModel):
    created_at: typing.Optional[datetime] = Field(None, alias='created_at')

    decision: typing.Optional[Decision] = Field(None, alias='decision')

    id: typing.Optional[str] = Field(None, alias='id')

    metadata: typing.Optional[DecisionLogMetadata] = Field(None, alias='metadata')

    policies: typing.Optional[DecisionLogPolicies] = Field(None, alias='policies')

    time_taken_ms: typing.Optional[int] = Field(None, alias='time_taken_ms')
    class Config:
        arbitrary_types_allowed = True
