# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from circle_ci_python_sdk.pydantic.insights_get_project_workflow_metrics_response_items_item_metrics_duration_metrics import InsightsGetProjectWorkflowMetricsResponseItemsItemMetricsDurationMetrics

class InsightsGetProjectWorkflowMetricsResponseItemsItemMetrics(BaseModel):
    # The total number of runs, including runs that are still on-hold or running.
    total_runs: int = Field(alias='total_runs')

    # The number of successful runs.
    successful_runs: int = Field(alias='successful_runs')

    # The mean time to recovery (mean time between failures and their next success) in seconds.
    mttr: typing.Optional[int] = Field(alias='mttr')

    # The total credits consumed by the workflow in the aggregation window. Note that Insights is not a real time financial reporting tool and should not be used for credit reporting.
    total_credits_used: typing.Optional[int] = Field(alias='total_credits_used')

    # The number of failed runs.
    failed_runs: int = Field(alias='failed_runs')

    success_rate: typing.Union[int, float] = Field(alias='success_rate')

    duration_metrics: InsightsGetProjectWorkflowMetricsResponseItemsItemMetricsDurationMetrics = Field(alias='duration_metrics')

    # The number of recovered workflow executions per day.
    total_recoveries: typing.Optional[int] = Field(alias='total_recoveries')

    # The average number of runs per day.
    throughput: typing.Union[int, float] = Field(alias='throughput')
    class Config:
        arbitrary_types_allowed = True
