# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from circle_ci_python_sdk.pydantic.insights_get_summary_metrics_with_trends_response_org_project_data_item_metrics import InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataItemMetrics
from circle_ci_python_sdk.pydantic.insights_get_summary_metrics_with_trends_response_org_project_data_item_trends import InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataItemTrends

class InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataItem(BaseModel):
    # The name of the project.
    project_name: str = Field(alias='project_name')

    metrics: InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataItemMetrics = Field(alias='metrics')

    trends: InsightsGetSummaryMetricsWithTrendsResponseOrgProjectDataItemTrends = Field(alias='trends')
    class Config:
        arbitrary_types_allowed = True
