# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from circle_ci_python_sdk.pydantic.insights_get_project_workflow_test_metrics_response_most_failed_tests import InsightsGetProjectWorkflowTestMetricsResponseMostFailedTests
from circle_ci_python_sdk.pydantic.insights_get_project_workflow_test_metrics_response_slowest_tests import InsightsGetProjectWorkflowTestMetricsResponseSlowestTests
from circle_ci_python_sdk.pydantic.insights_get_project_workflow_test_metrics_response_test_runs import InsightsGetProjectWorkflowTestMetricsResponseTestRuns

class InsightsGetProjectWorkflowTestMetricsResponse(BaseModel):
    # The average number of tests executed per run
    average_test_count: int = Field(alias='average_test_count')

    most_failed_tests: InsightsGetProjectWorkflowTestMetricsResponseMostFailedTests = Field(alias='most_failed_tests')

    # The number of tests with the same success rate being omitted from most_failed_tests
    most_failed_tests_extra: int = Field(alias='most_failed_tests_extra')

    slowest_tests: InsightsGetProjectWorkflowTestMetricsResponseSlowestTests = Field(alias='slowest_tests')

    # The number of tests with the same duration rate being omitted from slowest_tests
    slowest_tests_extra: int = Field(alias='slowest_tests_extra')

    # The total number of test runs
    total_test_runs: int = Field(alias='total_test_runs')

    test_runs: InsightsGetProjectWorkflowTestMetricsResponseTestRuns = Field(alias='test_runs')
    class Config:
        arbitrary_types_allowed = True
