# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class JobGetArtifactsResponseItemsItem(BaseModel):
    # The artifact path.
    path: str = Field(alias='path')

    # The index of the node that stored the artifact.
    node_index: int = Field(alias='node_index')

    # The URL to download the artifact contents.
    url: str = Field(alias='url')
    class Config:
        arbitrary_types_allowed = True
