# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from circle_ci_python_sdk.pydantic.json_duration import JSONDuration
from circle_ci_python_sdk.pydantic.patch_claims_request_audience import PatchClaimsRequestAudience

class PatchClaimsRequest(BaseModel):
    audience: typing.Optional[PatchClaimsRequestAudience] = Field(None, alias='audience')

    ttl: typing.Optional[JSONDuration] = Field(None, alias='ttl')
    class Config:
        arbitrary_types_allowed = True
