# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from circle_ci_python_sdk.pydantic.pipeline_get_all_pipelines_response_items_item_trigger_actor import PipelineGetAllPipelinesResponseItemsItemTriggerActor

class PipelineGetAllPipelinesResponseItemsItemTrigger(BaseModel):
    # The type of trigger.
    type: Literal["scheduled_pipeline", "explicit", "api", "webhook"] = Field(alias='type')

    # The date and time the trigger was received.
    received_at: datetime = Field(alias='received_at')

    actor: PipelineGetAllPipelinesResponseItemsItemTriggerActor = Field(alias='actor')
    class Config:
        arbitrary_types_allowed = True
