# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class PipelineListRecentPipelinesResponseItemsItemErrorsItem(BaseModel):
    # The type of error.
    type: Literal["config", "config-fetch", "timeout", "permission", "other", "plan"] = Field(alias='type')

    # A human-readable error message.
    message: str = Field(alias='message')
    class Config:
        arbitrary_types_allowed = True
