# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from circle_ci_python_sdk.pydantic.pipeline_get_all_pipelines_response_items_item_errors import PipelineGetAllPipelinesResponseItemsItemErrors
from circle_ci_python_sdk.pydantic.pipeline_get_all_pipelines_response_items_item_trigger import PipelineGetAllPipelinesResponseItemsItemTrigger
from circle_ci_python_sdk.pydantic.pipeline_get_all_pipelines_response_items_item_trigger_parameters import PipelineGetAllPipelinesResponseItemsItemTriggerParameters
from circle_ci_python_sdk.pydantic.pipeline_get_all_pipelines_response_items_item_vcs import PipelineGetAllPipelinesResponseItemsItemVcs

class PipelineGetAllPipelinesResponseItemsItem(BaseModel):
    # The unique ID of the pipeline.
    id: str = Field(alias='id')

    errors: PipelineGetAllPipelinesResponseItemsItemErrors = Field(alias='errors')

    # The project-slug for the pipeline.
    project_slug: str = Field(alias='project_slug')

    # The number of the pipeline.
    number: int = Field(alias='number')

    # The current state of the pipeline.
    state: Literal["created", "errored", "setup-pending", "setup", "pending"] = Field(alias='state')

    # The date and time the pipeline was created.
    created_at: datetime = Field(alias='created_at')

    trigger: PipelineGetAllPipelinesResponseItemsItemTrigger = Field(alias='trigger')

    # The date and time the pipeline was last updated.
    updated_at: typing.Optional[datetime] = Field(None, alias='updated_at')

    trigger_parameters: typing.Optional[PipelineGetAllPipelinesResponseItemsItemTriggerParameters] = Field(None, alias='trigger_parameters')

    vcs: typing.Optional[PipelineGetAllPipelinesResponseItemsItemVcs] = Field(None, alias='vcs')
    class Config:
        arbitrary_types_allowed = True
