# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Policy(BaseModel):
    content: typing.Optional[str] = Field(None, alias='content')

    created_at: typing.Optional[datetime] = Field(None, alias='created_at')

    created_by: typing.Optional[str] = Field(None, alias='created_by')

    name: typing.Optional[str] = Field(None, alias='name')
    class Config:
        arbitrary_types_allowed = True
