# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class RestrictionCreated(BaseModel):
    # UUID of the project restriction
    id: typing.Optional[str] = Field(None, alias='id')

    # Deprecated - For \"project\" restrictions read the project ID from \"restriction_value\" instead.  UUID of the project used in a project restriction. 
    project_id: typing.Optional[str] = Field(None, alias='project_id')

    # Contains a human-readable reference for the restriction. For \"project\" restrictions this is the name of the project.  May be null. 
    name: typing.Optional[str] = Field(None, alias='name')

    # Type of the restriction
    restriction_type: typing.Optional[Literal["project", "expression"]] = Field(None, alias='restriction_type')

    # Value used to evaluate the restriction
    restriction_value: typing.Optional[str] = Field(None, alias='restriction_value')
    class Config:
        arbitrary_types_allowed = True
