# coding: utf-8

"""
    CircleCI API

    This describes the resources that make up the CircleCI API v2.

    The version of the OpenAPI document: v2
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from circle_ci_python_sdk.pydantic.schedule_update_schedule_request_parameters import ScheduleUpdateScheduleRequestParameters
from circle_ci_python_sdk.pydantic.schedule_update_schedule_request_timetable import ScheduleUpdateScheduleRequestTimetable

class ScheduleUpdateScheduleRequest(BaseModel):
    # Description of the schedule.
    description: typing.Optional[typing.Optional[str]] = Field(None, alias='description')

    parameters: typing.Optional[ScheduleUpdateScheduleRequestParameters] = Field(None, alias='parameters')

    # Name of the schedule.
    name: typing.Optional[str] = Field(None, alias='name')

    timetable: typing.Optional[ScheduleUpdateScheduleRequestTimetable] = Field(None, alias='timetable')

    # The attribution-actor of the scheduled pipeline.
    attribution-actor_: typing.Optional[Literal["current", "system"]] = Field(None, alias='attribution-actor')
    class Config:
        arbitrary_types_allowed = True
